--[[
===========================
        PixelBees
===========================
A Roblox game project by Jasper Soete.
Started on: October 24, 2025

This is a passion project aimed at creating a fun and engaging experience centered around bees and pixel art. 
The game will feature various tools, flowers, and fun gameplay elements.
It is heavily inspired by Bee Swarm Simulator, but with a unique pixel art twist.

===========================

Documentation:

Nothing for now.
===========================
        PixelBees
===========================
]]
